# Generated by Django 4.0 on 2022-02-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_user_profile_delete_xabar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
