# Generated by Django 4.0 on 2022-02-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_remove_post_author_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='slug',
            field=models.SlugField(default=0, max_length=200, unique=True),
        ),
    ]
