# Generated by Django 4.0 on 2022-02-25 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_remove_post_author_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='App.user_profile'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
